(function(){
'use strict';
const PV=window.PV4,D=PV.D;
const FEMALE=new Set(['Alexia Putellas','Aitana Bonmatí','Khadija Shaw','Caroline Graham Hansen','Ewa Pajor','Mariona','Mapi León','Patri Guijarro','Yui Hasegawa','Klara Bühl','Barbra Banda','Melchie Dumornay','Tabitha Chawinga','Salma Paralluelo','Lauren Hemp','Sakina Karchaoui','Debinha','Rose Lavelle','Chloe Kelly','Guro Reiten','Lindsey Heaps','Georgia Stanway','Linda Caicedo','Alyssa Thompson','Leah Williamson','Alex Greenwood','Lucy Bronze','Kim Little','Taylor Flint','Racheal Kundananji']);
D.PLAYERS=D.PLAYERS.filter(p=>!FEMALE.has(p.name)&&!['OL Lyonnes','Gotham FC','Orlando Pride','Bay FC'].includes(p.club));
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const leagueMap={'Real Madrid':'LaLiga EA Sports','Atlético de Madrid':'LaLiga EA Sports','Manchester City':'Premier League','Arsenal':'Premier League','FC Bayern München':'Bundesliga','Bayern München':'Bundesliga','Inter':'Serie A','AC Milan':'Serie A','Galatasaray':'Süper Lig','LAFC':'MLS','Napoli':'Serie A'};
function quality(p){if(p.special)return{tier:'special',rare:true,cardType:'totw',rarityLabel:'Team of the Week'};const t=p.ovr>=75?'gold':p.ovr>=65?'silver':'bronze';const r=t==='gold'?(p.ovr>=82||p.pac>=90||p.price>=12000):t==='silver'?(p.ovr>=72||p.pac>=84):(p.ovr>=63||p.pac>=80);return{tier:t,rare:r,cardType:`${t}-${r?'rare':'common'}`,rarityLabel:`${t==='gold'?'Oro':t==='silver'?'Plata':'Bronce'} ${r?'premium':'común'}`}}
function add(name,pos,ovr,pac,sho,pas,dri,def,phy,nation,club,price,alt=[]){if(D.PLAYERS.some(p=>p.name===name))return;const p={id:slug(name),identity:slug(name),name,searchName:name,pos,ovr,pac,sho,pas,dri,def,phy,nation,club,league:leagueMap[club]||'Liga Internacional',price,target:Math.round(price*.75/100)*100,alt,simulated:false};Object.assign(p,quality(p));D.PLAYERS.push(p)}
add('Luis Díaz','MI',88,82,82,83,87,44,74,'Colombia','FC Bayern München',145000,['EI','DC']);
add('Lautaro Martínez','DC',87,80,88,76,85,51,74,'Argentina','Inter',95000,[]);
add('Jamal Musiala','MCO',87,79,81,79,90,62,65,'Alemania','FC Bayern München',120000,['MI','EI']);
add('Scott McTominay','MC',86,80,83,77,82,80,86,'Escocia','Napoli',55000,['MCD']);
add('Julián Alvarez','DC',86,86,86,82,87,58,77,'Argentina','Atlético de Madrid',105000,['MCO']);
add('Victor Osimhen','DC',85,89,84,65,78,51,86,'Nigeria','Galatasaray',65000,[]);
add('Phil Foden','MCO',84,77,82,82,88,57,53,'Inglaterra','Manchester City',42000,['MC','ED','MD']);
add('Rodrygo','EI',84,87,77,79,87,33,63,'Brasil','Real Madrid',55000,['ED','DC','MI']);
add('Trent Alexander-Arnold','LD',84,75,72,89,80,77,72,'Inglaterra','Real Madrid',45000,['MD']);
add('Son Heung Min','DC',81,81,81,79,80,41,74,'Corea del Sur','LAFC',16000,['EI','MCO','MI']);
add('David Raya','POR',88,87,86,88,88,58,86,'España','Arsenal',38000,[]);
add('Mike Maignan','POR',87,83,86,81,89,64,84,'Francia','AC Milan',32000,[]);
D.PLAYERS.forEach(p=>{p.league=p.league||leagueMap[p.club]||p.league||'Liga Internacional';Object.assign(p,quality(p));p.target=p.target||Math.max(200,Math.round((p.price||1000)*.74/100)*100)});
D.TOTW=D.PLAYERS.filter(p=>p.special);
if(!D.PACKS_V4.some(p=>p.id==='silver5'))D.PACKS_V4.push({id:'silver5',name:'5 Silver Players',subtitle:'5 jugadores plata · recompensa de SBC',cost:0,count:5,min:65,max:74,tag:'SILVER',tokenOnly:true});
if(!D.PACKS_V4.some(p=>p.id==='gold3'))D.PACKS_V4.push({id:'gold3',name:'3 Gold Players',subtitle:'3 jugadores oro · recompensa de SBC',cost:0,count:3,min:75,max:84,tag:'GOLD',tokenOnly:true});
D.LEAGUES=[...new Set(D.PLAYERS.map(p=>p.league))].sort();
const F={
'4-3-3':[{id:'LW',label:'EI',x:16,y:14},{id:'ST',label:'DC',x:50,y:10},{id:'RW',label:'ED',x:84,y:14},{id:'LCM',label:'MC',x:27,y:42},{id:'CM',label:'MC',x:50,y:48},{id:'RCM',label:'MC',x:73,y:42},{id:'LB',label:'LI',x:12,y:72},{id:'LCB',label:'DFC',x:37,y:68},{id:'RCB',label:'DFC',x:63,y:68},{id:'RB',label:'LD',x:88,y:72},{id:'GK',label:'POR',x:50,y:89}],
'4-2-3-1':[{id:'ST',label:'DC',x:50,y:10},{id:'LM',label:'MI',x:18,y:31},{id:'CAM',label:'MCO',x:50,y:31},{id:'RM',label:'MD',x:82,y:31},{id:'LCDM',label:'MCD',x:36,y:52},{id:'RCDM',label:'MCD',x:64,y:52},{id:'LB',label:'LI',x:12,y:74},{id:'LCB',label:'DFC',x:37,y:69},{id:'RCB',label:'DFC',x:63,y:69},{id:'RB',label:'LD',x:88,y:74},{id:'GK',label:'POR',x:50,y:89}],
'4-4-2':[{id:'LST',label:'DC',x:37,y:12},{id:'RST',label:'DC',x:63,y:12},{id:'LM',label:'MI',x:14,y:40},{id:'LCM',label:'MC',x:39,y:45},{id:'RCM',label:'MC',x:61,y:45},{id:'RM',label:'MD',x:86,y:40},{id:'LB',label:'LI',x:12,y:73},{id:'LCB',label:'DFC',x:37,y:68},{id:'RCB',label:'DFC',x:63,y:68},{id:'RB',label:'LD',x:88,y:73},{id:'GK',label:'POR',x:50,y:89}],
'4-3-2-1':[{id:'LF',label:'EI',x:28,y:22},{id:'ST',label:'DC',x:50,y:10},{id:'RF',label:'ED',x:72,y:22},{id:'LCM',label:'MC',x:27,y:48},{id:'CM',label:'MC',x:50,y:54},{id:'RCM',label:'MC',x:73,y:48},{id:'LB',label:'LI',x:12,y:74},{id:'LCB',label:'DFC',x:37,y:69},{id:'RCB',label:'DFC',x:63,y:69},{id:'RB',label:'LD',x:88,y:74},{id:'GK',label:'POR',x:50,y:89}],
'4-2-2-2':[{id:'LST',label:'DC',x:36,y:11},{id:'RST',label:'DC',x:64,y:11},{id:'LCAM',label:'MCO',x:25,y:36},{id:'RCAM',label:'MCO',x:75,y:36},{id:'LCDM',label:'MCD',x:37,y:54},{id:'RCDM',label:'MCD',x:63,y:54},{id:'LB',label:'LI',x:12,y:74},{id:'LCB',label:'DFC',x:37,y:69},{id:'RCB',label:'DFC',x:63,y:69},{id:'RB',label:'LD',x:88,y:74},{id:'GK',label:'POR',x:50,y:89}],
'3-5-2':[{id:'LST',label:'DC',x:37,y:11},{id:'RST',label:'DC',x:63,y:11},{id:'CAM',label:'MCO',x:50,y:31},{id:'LM',label:'MI',x:13,y:46},{id:'LCDM',label:'MCD',x:38,y:52},{id:'RCDM',label:'MCD',x:62,y:52},{id:'RM',label:'MD',x:87,y:46},{id:'LCB',label:'DFC',x:27,y:73},{id:'CB',label:'DFC',x:50,y:68},{id:'RCB',label:'DFC',x:73,y:73},{id:'GK',label:'POR',x:50,y:89}]
};
PV.FORMATIONS=F;PV.state.formation=PV.state.formation&&F[PV.state.formation]?PV.state.formation:'4-3-3';D.SLOTS=F[PV.state.formation];
PV.setFormation=name=>{if(!F[name]||name===PV.state.formation)return;const old=Object.values(PV.state.squad||{}).map(id=>PV.byId(id)).filter(Boolean);PV.state.formation=name;D.SLOTS=F[name];const sq={};for(const slot of D.SLOTS){const idx=old.findIndex(p=>PV.canPlay(p,slot.label)&&!PV.identityUsed(sq,p.id));if(idx>=0){sq[slot.id]=old[idx].id;old.splice(idx,1)}}PV.state.squad=sq;PV.state.draft=null;PV.save();PV.toast?.(`Formación ${name}`);PV.render?.()};
const oldPhoto=PV.photoFor;PV.photoFor=async p=>{if(PV.state.photos[p.id])return PV.state.photos[p.id];const aliases={'Vini Jr.':'Vinicius Junior','Kylian Mbappé':'Kylian Mbappe','Ousmane Dembélé':'Ousmane Dembele','Luis Díaz':'Luis Diaz','Julián Alvarez':'Julian Alvarez','Nicolò Barella':'Nicolo Barella'};const names=[p.searchName||p.name,aliases[p.name],p.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'')].filter(Boolean);for(const n of [...new Set(names)]){try{const r=await fetch(`https://www.thesportsdb.com/api/v1/json/3/searchplayers.php?p=${encodeURIComponent(n)}`),j=await r.json(),arr=j?.player||[],norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),target=norm(p.name),a=arr.find(x=>target.includes(norm(x.strPlayer))||norm(x.strPlayer).includes(target))||arr[0],url=a?.strCutout||a?.strThumb;if(url){PV.state.photos[p.id]=url;PV.save();return url}}catch{}}return oldPhoto?oldPhoto(p):null};
})();