(function(){
'use strict';
const PV=window.PV4,D=PV.D,$=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function resultScreen(pack,pulls){const o=$('#overlay');o.className='overlay';o.innerHTML=`<div class="results pv6-results"><div class="results-head"><div><span class="eyebrow">${PV.esc(pack.name)}</span><h2>Contenido</h2></div><span class="chip">${pulls.length} ITEMS</span></div><div class="result-grid">${pulls.map(p=>PV.card(p,{mini:true,count:PV.state.collection[p.id],button:false})).join('')}</div><div class="results-actions"><button class="btn-ghost" data-close-results>AL CLUB</button><button class="btn" data-again="${pack.id}">OTRO PACK</button></div></div>`;PV.hydrate(o)}
function packScene(pack){const o=$('#overlay');o.className=`opening pv6-pack-opening ${pack.specialOnly?'special':''}`;o.innerHTML=`<div class="pv6-pack-glow"></div><div class="pv6-pack-wrap"><div class="pv6-pack-shell"><div class="pv6-pack-lines"></div><b>${pack.specialOnly?'IF':'27'}</b><small>${PV.esc(pack.tag||'PACK')}</small></div><div class="pv6-pack-rip"></div></div>`;return o}
async function basicAnimation(pack){const o=packScene(pack);await sleep(280);o.querySelector('.pv6-pack-wrap')?.classList.add('tear');await sleep(520);o.classList.add('flash');await sleep(180)}
function cinemaMarkup(){return `<div class="cinema-bg"></div><div class="gate gate-l"></div><div class="gate gate-r"></div><div class="beam beam-l"></div><div class="beam beam-r"></div><div class="floor-ring"></div><div id="pv6Reveal" class="cinema-reveal"></div><div class="skip-clean">TOCA PARA ACELERAR</div>`}
async function walkout(pack,pulls){const best=pulls[0],special=!!best.special,elite=best.ovr>=90,high=best.ovr>=87,o=$('#overlay');o.className=`opening cinematic pv6-cinema ${special?'totw':''} ${elite?'elite':''}`;o.innerHTML=cinemaMarkup();const r=$('#pv6Reveal');let fast=false,start=Date.now();o.onclick=e=>{if(e.target.closest('[data-close-results],[data-again]'))return;if(Date.now()-start>1500)fast=true};const mult=special?1.12:elite?1.08:high?1:.9,wait=ms=>sleep(fast?Math.min(85,ms):Math.round(ms*mult));r.innerHTML='<div class="reveal-mark"></div>';await wait(420);r.innerHTML=`<div class="reveal-token flag-token">${PV.flag(best.nation)}</div>`;await wait(650);r.innerHTML=`<div class="reveal-token text-token">${best.pos}</div>`;await wait(610);r.innerHTML=`<div class="reveal-token club-token">${PV.clubAbbr(best.club)}</div>`;await wait(650);const floor=Math.max(82,best.ovr-(elite?7:5));for(let n=floor;n<=best.ovr;n++){r.innerHTML=`<div class="rating-step">${n}</div>`;await wait(n===best.ovr?420:125)}if(special){r.innerHTML='<div class="if-stamp"><span>IF</span><small>TEAM OF THE WEEK</small></div>';await wait(600)}r.innerHTML=`<div class="walkout-card">${PV.card(best)}</div>`;PV.hydrate(r);try{navigator.vibrate?.(special?[35,25,60]:[25,20,35])}catch{}await wait(920);resultScreen(pack,pulls)}
PV.openPack=async id=>{const pack=D.PACKS_V4.find(p=>p.id===id);if(!pack)return;const a=PV.packAccess(pack);if(!a.ok)return PV.toast(a.label==='MAÑANA'?'El Daily vuelve mañana':pack.tokenOnly?'Se consigue como recompensa':'No tienes coins suficientes');PV.consumePack(pack);const pulls=PV.makePack(pack);pulls.forEach(PV.addPlayer);PV.state.xp+=Math.max(0,pulls[0].ovr-80)*5;PV.save();await basicAnimation(pack);if(pulls[0].special||pulls[0].ovr>=85)await walkout(pack,pulls);else resultScreen(pack,pulls)};
})();