(function(){
'use strict';
const PV=window.PV4,D=PV.D,$=s=>document.querySelector(s);
PV.state.sbcBuilds=PV.state.sbcBuilds||{};PV.ui.sbcActive=PV.ui.sbcActive||null;
function threshold(n,a,b,c){return n>=c?3:n>=b?2:n>=a?1:0}
PV.metricsForSlots=(squad,slots)=>{const valid=[];for(const slot of slots){const id=squad?.[slot.id],p=PV.byId(id);if(p&&PV.canPlay(p,slot.label)&&!valid.some(x=>x.p.identity===p.identity))valid.push({slot,p})}const clubs={},nations={},leagues={};valid.forEach(x=>{clubs[x.p.club]=(clubs[x.p.club]||0)+1;nations[x.p.nation]=(nations[x.p.nation]||0)+1;leagues[x.p.league]=(leagues[x.p.league]||0)+1});const per={};let raw=0;valid.forEach(({slot,p})=>{const c=threshold(clubs[p.club]||0,2,4,7),n=threshold(nations[p.nation]||0,2,5,8),l=threshold(leagues[p.league]||0,3,5,8),chem=Math.min(3,c+n+l);per[slot.id]=chem;raw+=chem});const rating=valid.length?Math.round(valid.reduce((s,x)=>s+x.p.ovr,0)/valid.length):0,chemistry=Math.round(raw/33*100);return{rating,chemistry,total:Math.min(199,rating+chemistry),raw,per,valid:valid.length,clubs,nations,leagues}}
function pitchPlayer(slot,squad,metrics,attr='data-slot'){const p=PV.byId(squad?.[slot.id]),chem=metrics.per?.[slot.id]||0;if(!p)return `<button class="pv6-field-slot empty" style="left:${slot.x}%;top:${slot.y}%" ${attr}="${slot.id}"><span>＋</span><b>${slot.label}</b></button>`;const photo=PV.state.photos[p.id];return `<button class="pv6-field-slot" style="left:${slot.x}%;top:${slot.y}%" ${attr}="${slot.id}"><span class="pv6-field-card ${p.special?'special':''}"><span class="fc-rating">${p.ovr}<small>${p.pos}</small></span><span class="fc-face" data-photo="${p.id}">${photo?`<img src="${PV.esc(photo)}" alt="">`:`<b>${PV.ini(p.name)}</b>`}</span><span class="fc-name">${PV.esc(p.name)}</span><span class="fc-chem">${[1,2,3].map(i=>`<i class="${i<=chem?'on':''}"></i>`).join('')}</span></span></button>`}
function renderSquad(){const m=PV.squadMetrics(PV.state.squad),form=PV.state.formation||'4-3-3';$('#screen').innerHTML=`<div class="scroll pv6-squad-screen"><div class="squad-top pv6-squad-top"><div><span class="eyebrow">PLANTILLA ACTIVA</span><h2>Mi XI</h2></div><label class="formation-picker"><span>FORMACIÓN</span><select id="formationSelect">${Object.keys(PV.FORMATIONS).map(x=>`<option ${x===form?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="pv6-scorebar"><span><b>${m.rating}</b><small>GRL</small></span><span><b>${m.chemistry}</b><small>QUÍMICA</small></span><span class="total"><b>${m.total}</b><small>/199</small></span></div><div class="pitch pv6-pitch">${D.SLOTS.map(s=>pitchPlayer(s,PV.state.squad,m)).join('')}</div><div class="pv6-squad-note"><b>${form}</b> · Toca una posición para cambiar jugador. Las cartas de campo priorizan cara, media y química para que el XI se lea de un vistazo.</div><div class="squad-actions"><button class="btn-ghost" data-clear-xi>VACIAR</button><button class="btn" data-auto-xi>AUTO XI</button></div></div>`;PV.hydrate($('#screen'))}
const SBC_FORM=PV.FORMATIONS['4-4-2'];
PV.SBC_MANUAL=[
{id:'bronze-links',name:'Conexiones de bronce',group:'Fundamentos',desc:'Tu primer DCP manual. Solo duplicados bronce.',reward:'gold3',req:{rating:62,chem:18,tier:'bronze',nations:3}},
{id:'silver-squad',name:'Once de plata',group:'Fundamentos',desc:'Construye un XI completo de platas repetidas.',reward:'premium',req:{rating:69,chem:24,tier:'silver',leagues:2}},
{id:'hybrid-nations',name:'Híbrido de Naciones',group:'Avanzados',desc:'Mezcla nacionalidades sin perder demasiada química.',reward:'82x3',req:{rating:76,chem:42,nations:5,leagues:3}},
{id:'elite-exchange',name:'Desafío 83',group:'Mejoras',desc:'Plantilla fuerte de duplicados para perseguir un TOTW.',reward:'totw',req:{rating:83,chem:48,highOvr:86,highCount:2}}
];
function build(id){return PV.state.sbcBuilds[id]||(PV.state.sbcBuilds[id]={})}
function selectedCounts(b){const x={};Object.values(b||{}).forEach(id=>x[id]=(x[id]||0)+1);return x}
function availableDupeIds(b,exceptSlot=null){const sel=selectedCounts(Object.fromEntries(Object.entries(b||{}).filter(([k])=>k!==exceptSlot)));return PV.owned().filter(({count,p})=>Math.max(0,count-1-(sel[p.id]||0))>0).map(x=>x.p)}
function sbcEval(ch,b){const m=PV.metricsForSlots(b,SBC_FORM),players=Object.values(b||{}).map(PV.byId).filter(Boolean),nations=new Set(players.map(p=>p.nation)).size,leagues=new Set(players.map(p=>p.league)).size,high=players.filter(p=>p.ovr>=(ch.req.highOvr||100)).length,r=ch.req;const checks=[['11 jugadores',players.length===11],...[r.rating?[`GRL ${r.rating}+`,players.length===11&&m.rating>=r.rating]:null,r.chem?[`Química ${r.chem}+`,m.chemistry>=r.chem]:null,r.tier?[`Solo ${r.tier==='bronze'?'bronce':'plata'}`,players.length===11&&players.every(p=>p.tier===r.tier)]:null,r.nations?[`${r.nations}+ naciones`,nations>=r.nations]:null,r.leagues?[`${r.leagues}+ ligas`,leagues>=r.leagues]:null,r.highCount?[`${r.highCount}× ${r.highOvr}+`,high>=r.highCount]:null].filter(Boolean)];return{m,players,nations,leagues,checks,ok:checks.every(x=>x[1])}}
function sbcList(){return `<div class="scroll"><div class="section-head"><div><span class="eyebrow">SBC / DCP</span><h2>Desafíos</h2><p>Plantillas manuales con requisitos. Solo usamos duplicados, así tu última copia queda protegida.</p></div></div><div class="dupe-bank"><b>${PV.dupeCount()} duplicados disponibles</b><p>Los repetidos funcionan como almacenamiento SBC.</p></div><div class="pv6-sbc-list">${PV.SBC_MANUAL.map(ch=>{const e=sbcEval(ch,build(ch.id)),pack=D.PACKS_V4.find(p=>p.id===ch.reward);return `<button class="pv6-sbc-item" data-sbc-open="${ch.id}"><span class="sbc-icon">${e.ok?'✓':'XI'}</span><span><small>${ch.group}</small><b>${PV.esc(ch.name)}</b><em>${PV.esc(ch.desc)}</em></span><span class="sbc-reward">${PV.esc(pack?.name||ch.reward)}<small>${Object.keys(build(ch.id)).length}/11</small></span></button>`}).join('')}</div></div>`}
function sbcBuilder(ch){const b=build(ch.id),e=sbcEval(ch,b),pack=D.PACKS_V4.find(p=>p.id===ch.reward);return `<div class="scroll pv6-sbc-builder"><div class="pv6-sbc-header"><button class="chip" data-sbc-back>‹ VOLVER</button><div><span class="eyebrow">${ch.group}</span><h2>${PV.esc(ch.name)}</h2></div><span class="reward-tag">${PV.esc(pack?.name||ch.reward)}</span></div><div class="pv6-reqs">${e.checks.map(([t,ok])=>`<span class="${ok?'ok':''}">${ok?'✓':'○'} ${t}</span>`).join('')}</div><div class="pv6-sbc-metrics"><span><b>${e.m.rating}</b>GRL</span><span><b>${e.m.chemistry}</b>QUÍMICA</span><span><b>${e.players.length}</b>/11</span></div><div class="pitch pv6-pitch pv6-sbc-pitch">${SBC_FORM.map(s=>pitchPlayer(s,b,e.m,'data-sbc-slot')).join('')}</div><div class="pv6-sbc-actions"><button class="btn-ghost" data-sbc-clear>VACIAR</button><button class="btn-ghost" data-sbc-auto>AUTOCOMPLETAR</button><button class="btn" data-sbc-submit ${e.ok?'':'disabled'}>ENTREGAR</button></div><p class="pv6-warning">Al entregar, las copias seleccionadas desaparecen del almacenamiento de duplicados. La última copia del club nunca se toca.</p></div>`}
function renderSbc(){const ch=PV.SBC_MANUAL.find(x=>x.id===PV.ui.sbcActive);$('#screen').innerHTML=ch?sbcBuilder(ch):sbcList();PV.hydrate($('#screen'))}
PV.openSbcSlot=slotId=>{const ch=PV.SBC_MANUAL.find(x=>x.id===PV.ui.sbcActive);if(!ch)return;const b=build(ch.id),slot=SBC_FORM.find(s=>s.id===slotId),a=availableDupeIds(b,slotId).filter(p=>PV.canPlay(p,slot.label)).sort((a,b)=>b.ovr-a.ovr);PV.openSheet(`<span class="eyebrow">SBC · ${slot.label}</span><h2 style="margin:4px 0 10px">Elige un duplicado</h2>${a.length?`<div class="picker-grid">${a.map(p=>PV.card(p,{mini:true,button:false,count:PV.state.collection[p.id]})).join('')}</div>`:'<div class="empty">No tienes duplicados compatibles con esta posición.</div>'}`);[...$('#sheetBody').querySelectorAll('.pv6-mini')].forEach((c,i)=>c.onclick=()=>{b[slotId]=a[i].id;PV.save();PV.closeSheet();PV.render()})};
PV.autoSbc=()=>{const ch=PV.SBC_MANUAL.find(x=>x.id===PV.ui.sbcActive);if(!ch)return;const b={},used={};for(const slot of SBC_FORM){const candidates=PV.owned().filter(({count,p})=>PV.canPlay(p,slot.label)&&count-1-(used[p.id]||0)>0).map(x=>x.p).filter(p=>!ch.req.tier||p.tier===ch.req.tier).sort((a,b)=>a.ovr-b.ovr);let pick=candidates[0];if(!pick&&ch.req.tier)pick=PV.owned().filter(({count,p})=>PV.canPlay(p,slot.label)&&count-1-(used[p.id]||0)>0).map(x=>x.p).sort((a,b)=>a.ovr-b.ovr)[0];if(pick){b[slot.id]=pick.id;used[pick.id]=(used[pick.id]||0)+1}}PV.state.sbcBuilds[ch.id]=b;PV.save();PV.render()};
PV.submitManualSbc=()=>{const ch=PV.SBC_MANUAL.find(x=>x.id===PV.ui.sbcActive);if(!ch)return;const b=build(ch.id),e=sbcEval(ch,b);if(!e.ok)return PV.toast('La plantilla no cumple los requisitos');const counts=selectedCounts(b);for(const [id,n] of Object.entries(counts)){if((PV.state.collection[id]||0)-n<1)return PV.toast('Falta una copia duplicada')}for(const [id,n] of Object.entries(counts))for(let i=0;i<n;i++)PV.removeOne(id);PV.state.sbcCardsSubmitted+=11;PV.state.sbcCompletions[ch.id]=(PV.state.sbcCompletions[ch.id]||0)+1;PV.state.packTokens[ch.reward]=(PV.state.packTokens[ch.reward]||0)+1;PV.state.sbcBuilds[ch.id]={};PV.state.xp+=180;PV.save();PV.ui.sbcActive=null;PV.toast(`SBC completado · ${D.PACKS_V4.find(p=>p.id===ch.reward)?.name}`);PV.render()};
const oldRender=PV.render;PV.render=()=>{D.SLOTS=PV.FORMATIONS[PV.state.formation||'4-3-3'];oldRender();document.querySelectorAll('[data-nav="academy"]').forEach(x=>x.remove());if(PV.ui.screen==='squad')renderSquad();if(PV.ui.screen==='sbc')renderSbc()};
document.addEventListener('change',e=>{if(e.target.id==='formationSelect')PV.setFormation(e.target.value)});
document.addEventListener('click',e=>{const open=e.target.closest('[data-sbc-open]');if(open){PV.ui.sbcActive=open.dataset.sbcOpen;return PV.render()}if(e.target.closest('[data-sbc-back]')){PV.ui.sbcActive=null;return PV.render()}const slot=e.target.closest('[data-sbc-slot]');if(slot)return PV.openSbcSlot(slot.dataset.sbcSlot);if(e.target.closest('[data-sbc-clear]')){const ch=PV.ui.sbcActive;if(ch){PV.state.sbcBuilds[ch]={};PV.save();PV.render()}return}if(e.target.closest('[data-sbc-auto]'))return PV.autoSbc();if(e.target.closest('[data-sbc-submit]'))return PV.submitManualSbc()});
})();