(function(){
'use strict';
const PV=window.PV4;
const esc=PV.esc;
const STATS=p=>[['RIT',p.pac],['TIR',p.sho],['PAS',p.pas],['REG',p.dri],['DEF',p.def],['FÍS',p.phy]];
const silhouette=()=>'<span class="pv13-silhouette" aria-hidden="true"><i></i><b></b></span>';
const chem=n=>n===null?'':`<span class="pv13-chem" aria-label="${n} química">${[1,2,3].map(i=>`<i class="${i<=n?'on':''}"></i>`).join('')}</span>`;
function art(p){const u=PV.state.photos[p.id],src=PV.state.photoSourcesV12?.[p.id]||'cutout';return `<div class="pv7-photo pv13-art" data-photo="${p.id}">${u?`<img class="pv12-player-art pv12-art-${src}" src="${esc(u)}" alt="" loading="lazy" decoding="async">`:silhouette()}</div>`}
function club(p){const u=PV.clubLogoSync?.(p.club);return `<span class="pv8-club pv13-club" data-club-badge="${esc(p.club)}" title="${esc(p.club)}">${u?`<img src="${esc(u)}" alt="${esc(p.club)}">`:`<b>${PV.clubAbbr(p.club)}</b>`}</span>`}
function league(p){const u=PV.state.leagueLogos?.[p.league];return `<span class="pv8-league pv13-league" data-league-badge="${esc(p.league)}" title="${esc(p.league)}">${u?`<img src="${esc(u)}" alt="${esc(p.league)}">`:`<b>${String(p.league||'L').split(/\s+/).map(x=>x[0]).join('').slice(0,3)}</b>`}</span>`}
function body(p,chemistry){return `<span class="pv13-material" aria-hidden="true"></span><span class="pv7-frame pv13-frame" aria-hidden="true"></span><div class="pv7-rating pv13-rating"><b>${p.ovr}</b><small>${p.pos}</small></div><span class="pv7-quality pv13-quality" aria-label="${esc(p.rarityLabel||'')}">${p.special?'IF':p.rare?'◆':''}</span>${art(p)}<div class="pv7-name pv13-name">${esc(p.name)}</div><div class="pv7-stats pv13-stats">${STATS(p).map(([k,v])=>`<span><small>${k}</small><b>${v}</b></span>`).join('')}</div><div class="pv7-idrow pv13-idrow"><span class="pv7-flag pv13-flag">${PV.flag(p.nation)}</span>${league(p)}${club(p)}${chem(chemistry)}</div>`}
PV.card=(p,o={})=>{const count=o.count||0,chemistry=o.chem??null,cls=PV.cardClass(p),mini=!!o.mini,el=mini?(o.button===false?'div':'button'):'article',data=mini&&o.button!==false?` data-player="${p.id}"`:'';return `<${el} class="${mini?'mini-card pv6-mini pv7-mini':'pv6-card pv7-full'} pv7-card pv8-card pv9-card pv13-card ${cls}"${data} aria-label="${esc(p.name)} ${p.ovr} ${esc(p.rarityLabel||'')}">${count>1?`<span class="dupe pv13-dupe">x${count}</span>`:''}${body(p,chemistry)}</${el}>`};
PV.fieldCard=(p,chemistry=0)=>{const cls=PV.cardClass(p),u=PV.state.photos[p.id],src=PV.state.photoSourcesV12?.[p.id]||'cutout',cu=PV.clubLogoSync?.(p.club);return `<span class="pv8-field-card pv9-field-card pv13-field ${cls}"><span class="pv8-field-frame pv13-field-frame"></span><span class="pv8-field-rating pv13-field-rating">${p.ovr}<small>${p.pos}</small></span><span class="pv8-field-face pv13-field-art" data-photo="${p.id}">${u?`<img class="pv12-player-art pv12-art-${src}" src="${esc(u)}" alt="">`:silhouette()}</span><span class="pv8-field-name pv13-field-name">${esc(p.name)}</span><span class="pv8-field-bottom pv13-field-bottom"><span>${PV.flag(p.nation)}</span><span class="pv8-field-club pv13-field-club" data-club-badge="${esc(p.club)}">${cu?`<img src="${esc(cu)}" alt="${esc(p.club)}">`:`<b>${PV.clubAbbr(p.club)}</b>`}</span>${chem(chemistry)}</span></span>`};
window.PV13_CARD_AUDIT={renderer:'canonical-v13',types:['bronze-common','bronze-rare','silver-common','silver-rare','gold-common','gold-rare','totw'],contexts:['pack','club','picker','sbc','draft','xi']};
})();