(function(){
'use strict';
const PV=window.PV4;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(fc|cf|sad|r|real club|club de futbol|futbol club)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const TEAM_ALIASES={
'CE Sabadell FC':['Sabadell','CE Sabadell'],'Girona FC':['Girona'],'RCD Mallorca':['Mallorca','RCD Mallorca'],'UD Las Palmas':['Las Palmas'],'UD Almería':['Almeria','UD Almeria'],'R. Valladolid CF':['Real Valladolid','Valladolid'],'SD Eibar':['Eibar'],'Cádiz CF':['Cadiz','Cádiz'],'CD Leganés':['Leganes','Leganés'],'Granada CF':['Granada'],'Real Sociedad B':['Real Sociedad B','Real Sociedad II'],'Albacete BP':['Albacete'],'Córdoba CF':['Cordoba','Córdoba'],'Burgos CF':['Burgos'],'AD Ceuta FC':['Ceuta','AD Ceuta'],'CD Castellón':['Castellon','Castellón'],'CD Eldense':['Eldense'],'FC Andorra':['Andorra'],'Celta Fortuna':['Celta Fortuna','Celta Vigo B'],'R. Oviedo':['Real Oviedo','Oviedo'],'Sporting Gijón':['Sporting Gijon','Sporting Gijón','Real Sporting'],'CD Tenerife':['Tenerife']};
const PLAYER_ALIASES={'Viktor Tsygankov':['Viktor Tsyhankov'],'Dinko Horkaš':['Dinko Horkas'],'Álvaro Tejero':['Alvaro Tejero'],'Álex Muñoz':['Alex Munoz'],'Rubén Alcaraz':['Ruben Alcaraz'],'José Arnáiz':['Jose Arnaiz'],'Raíllo':['Antonio Raillo'],'Samú Costa':['Samu Costa'],'Àlex Corredera':['Alex Corredera'],'Jérémy Mellot':['Jeremy Mellot'],'José Gragera':['Jose Gragera'],'Aarón Escandell':['Aaron Escandell']};
function teamKeys(team){return [team,...(TEAM_ALIASES[team]||[])].map(norm).filter(Boolean)}
function nameKeys(p){return [p.searchName||p.name,p.name,...(PLAYER_ALIASES[p.name]||[])].map(norm).filter(Boolean)}
function teamMatch(actual,target){const a=norm(actual);if(!a)return false;return teamKeys(target).some(k=>a===k||a.includes(k)||k.includes(a))}
function nameMatch(actual,p){const a=norm(actual);if(!a)return false;return nameKeys(p).some(k=>a===k||a.includes(k)||k.includes(a))}
// v0.8 accepted loose name-only fallbacks. Purge that cache once, but never again after a newer match policy exists.
if(Number(PV.state.assetMatchVersion||0)<9){PV.state.photos={};PV.state.assetMatchVersion=9;PV.save?.()}
const sabadell='https://drop-assets.ea.com/images/aIrhRNIaKr0UWY3sbwxHo/1fa8ec800517b3804005ad84e26c4d80/l15021.png';
PV.clubLogoSync=club=>club==='CE Sabadell FC'?sabadell:(PV.state.clubLogos?.[club]||null);
PV.clubLogoFor=async club=>{if(!club)return null;if(club==='CE Sabadell FC')return sabadell;PV.state.clubLogos=PV.state.clubLogos||{};if(PV.state.clubLogos[club])return PV.state.clubLogos[club];for(const q0 of [club,...(TEAM_ALIASES[club]||[])]){try{const r=await fetch(`https://www.thesportsdb.com/api/v1/json/123/searchteams.php?t=${encodeURIComponent(q0)}`),j=await r.json(),teams=j?.teams||[],t=teams.find(x=>teamMatch(x.strTeam,club)||teamMatch(x.strTeamAlternate,club)),url=t?.strBadge||t?.strLogo||null;if(url){PV.state.clubLogos[club]=url;PV.save();return url}}catch{}}return null};
PV.photoFor=async p=>{if(!p)return null;if(PV.state.photos[p.id])return PV.state.photos[p.id];for(const q0 of [p.name,...(PLAYER_ALIASES[p.name]||[])]){try{const r=await fetch(`https://www.thesportsdb.com/api/v1/json/123/searchplayers.php?p=${encodeURIComponent(q0)}`),j=await r.json(),arr=j?.player||[];const a=arr.find(x=>nameMatch(x.strPlayer,p)&&teamMatch(x.strTeam,p.club));const url=a?.strCutout||a?.strThumb||null;if(url){PV.state.photos[p.id]=url;PV.save();return url}}catch{}}return null};
const oldHydrate=PV.hydrate;PV.hydrate=root=>{oldHydrate?.(root);const scope=root||document;const clubs=[...new Set([...scope.querySelectorAll('[data-club-badge]')].map(n=>n.dataset.clubBadge))].slice(0,12);clubs.forEach(async club=>{const url=await PV.clubLogoFor(club);if(!url)return;document.querySelectorAll(`[data-club-badge="${CSS.escape(club)}"]`).forEach(n=>n.innerHTML=`<img src="${PV.esc(url)}" alt="" loading="lazy">`)});const ids=[...new Set([...scope.querySelectorAll('[data-photo]')].map(n=>n.dataset.photo))].slice(0,12);ids.forEach(async id=>{const p=PV.byId(id);if(!p||PV.state.photos[id])return;const url=await PV.photoFor(p);if(!url)return;document.querySelectorAll(`[data-photo="${CSS.escape(id)}"]`).forEach(n=>n.innerHTML=`<img src="${PV.esc(url)}" alt="" loading="lazy" decoding="async">`)})};
})();