(function(){
'use strict';
const PV=window.PV4;
const stats=p=>[['RIT',p.pac],['TIR',p.sho],['PAS',p.pas],['REG',p.dri],['DEF',p.def],['FÍS',p.phy]];
const chemDots=n=>`<span class="pv7-chem">${[1,2,3].map(i=>`<i class="${i<=n?'on':''}"></i>`).join('')}</span>`;
const silhouette=()=>'<span class="pv7-silhouette" aria-hidden="true"><i></i><b></b></span>';
const photo=p=>{const u=PV.state.photos[p.id];return `<div class="pv7-photo" data-photo="${p.id}">${u?`<img src="${PV.esc(u)}" alt="" loading="lazy" decoding="async">`:silhouette()}</div>`};
const clubBadge=p=>{const u=PV.clubLogoSync?.(p.club);return `<span class="pv8-club" data-club-badge="${PV.esc(p.club)}">${u?`<img src="${PV.esc(u)}" alt="">`:`<b>${PV.clubAbbr(p.club)}</b>`}</span>`};
const leagueBadge=p=>{const u=PV.state.leagueLogos?.[p.league];return `<span class="pv8-league" data-league-badge="${PV.esc(p.league)}">${u?`<img src="${PV.esc(u)}" alt="">`:'<b>LL</b>'}</span>`};
function body(p,chem){return `<span class="pv7-frame" aria-hidden="true"></span><div class="pv7-rating"><b>${p.ovr}</b><small>${p.pos}</small></div><span class="pv7-quality">${p.special?'TOTW':p.rare?'PREM.':''}</span>${photo(p)}<div class="pv7-name">${PV.esc(p.name)}</div><div class="pv7-stats">${stats(p).map(([k,v])=>`<span><small>${k}</small><b>${v}</b></span>`).join('')}</div><div class="pv7-idrow"><span class="pv7-flag">${PV.flag(p.nation)}</span>${leagueBadge(p)}${clubBadge(p)}${chem!==null?chemDots(chem):''}</div>`}
PV.card=(p,o={})=>{const count=o.count||0,chem=o.chem??null,cls=PV.cardClass(p),mini=!!o.mini;if(mini){const el=o.button===false?'div':'button',data=o.button===false?'':` data-player="${p.id}"`;return `<${el} class="mini-card pv6-mini pv7-card pv7-mini pv8-card pv9-card ${cls}"${data} aria-label="${PV.esc(p.name)} ${p.ovr}">${count>1?`<span class="dupe">x${count}</span>`:''}${body(p,chem)}</${el}>`}return `<article class="pv6-card pv7-card pv7-full pv8-card pv9-card ${cls}" aria-label="${PV.esc(p.name)} ${p.ovr}">${body(p,chem)}</article>`};
PV.fieldCard=(p,chem=0)=>{const cls=PV.cardClass(p),u=PV.state.photos[p.id],club=PV.clubLogoSync?.(p.club);return `<span class="pv8-field-card pv9-field-card ${cls}"><span class="pv8-field-frame"></span><span class="pv8-field-rating">${p.ovr}<small>${p.pos}</small></span><span class="pv8-field-face" data-photo="${p.id}">${u?`<img src="${PV.esc(u)}" alt="">`:silhouette()}</span><span class="pv8-field-name">${PV.esc(p.name)}</span><span class="pv8-field-bottom"><span>${PV.flag(p.nation)}</span><span class="pv8-field-club" data-club-badge="${PV.esc(p.club)}">${club?`<img src="${PV.esc(club)}" alt="">`:`<b>${PV.clubAbbr(p.club)}</b>`}</span>${chemDots(chem)}</span></span>`};
})();