(function(){
'use strict';
const PV=window.PV4,D=PV.D,$=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function tone(f=440,d=.08){try{const C=window.AudioContext||window.webkitAudioContext,c=tone.c||(tone.c=new C),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.014;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}}
function overlayBase(cls=''){const o=$('#overlay');o.className=`opening ${cls}`;o.innerHTML='<div class="tunnel"></div><div class="lights"></div><div id="reveal" class="reveal"></div><div class="skip">TOCA PARA ACELERAR · EL HYPE NO SE SALTA AL INSTANTE</div>';return o}
function results(pack,pulls){const o=$('#overlay');o.className='overlay';o.innerHTML=`<div class="results"><div class="results-head"><div><span class="eyebrow">${PV.esc(pack.name)}</span><h2>Contenido</h2></div><span class="chip">${pulls.length} ITEMS</span></div><div class="result-grid">${pulls.map(p=>PV.card(p,{mini:true,count:PV.state.collection[p.id],button:false})).join('')}</div><div class="results-actions"><button class="btn-ghost" data-close-results>AL CLUB</button><button class="btn" data-again="${pack.id}">OTRO PACK</button></div></div>`;PV.hydrate(o)}
async function slowReveal(pack,pulls){const best=pulls[0],special=best.special,cls=special?'walkout totw':'walkout',o=overlayBase(cls),r=$('#reveal'),start=Date.now();let skip=false;o.onclick=e=>{if(e.target.closest('[data-close-results],[data-again]'))return;if(Date.now()-start>1200)skip=true};const wait=async ms=>sleep(skip?Math.min(120,ms):ms),base=special?900:best.ovr>=89?820:680;r.innerHTML='<div class="big">?</div><div class="sub">LAS LUCES SE APAGAN…</div>';tone(170,.18);await wait(base);r.innerHTML=`<div class="flag">${PV.flag(best.nation)}</div><div class="label">${PV.esc(best.nation)}</div><div class="sub">NACIONALIDAD</div>`;tone(260);await wait(base);r.innerHTML=`<div class="big" style="font-size:58px">${best.pos}</div><div class="sub">POSICIÓN</div>`;tone(330);await wait(base);r.innerHTML=`<div class="clubbig">${PV.clubAbbr(best.club)}</div><div class="label">${PV.esc(best.club)}</div><div class="sub">${PV.esc(best.league)}</div>`;tone(430);await wait(base);let floor=Math.max(75,best.ovr-4);for(let n=floor;n<best.ovr;n++){r.innerHTML=`<div class="big">${n}</div><div class="sub">OVERALL</div>`;tone(470+n*3,.035);await wait(special?240:180)}r.innerHTML=`<div class="big">${best.ovr}</div><div class="label">${special?'TEAM OF THE WEEK':'WALKOUT'}</div><div class="sub">AGUANTA…</div>`;tone(special?920:760,.16);try{navigator.vibrate?.(special?[60,35,80]:[45,25,55])}catch{}await wait(special?1100:850);const photo=await PV.photoFor(best);r.innerHTML=`<div class="final-card">${PV.card(best)}</div>`;PV.hydrate(r);await wait(special?1250:900);results(pack,pulls)}
async function quickReveal(pack,pulls){const o=overlayBase('fast'),r=$('#reveal');r.innerHTML=`<div class="big" style="font-size:45px">${pack.tag}</div><div class="sub">PACK OPENED</div>`;tone(360,.07);await sleep(260);results(pack,pulls)}
PV.openPack=async id=>{const pack=D.PACKS_V4.find(p=>p.id===id);if(!pack)return;const access=PV.packAccess(pack);if(!access.ok)return PV.toast(access.label==='MAÑANA'?'El Daily vuelve mañana':pack.tokenOnly?'Se consigue en objetivos, Draft o SBC':'No tienes coins suficientes');PV.consumePack(pack);const pulls=PV.makePack(pack);pulls.forEach(p=>PV.addPlayer(p));PV.state.xp+=Math.max(0,pulls[0].ovr-80)*5;PV.save();const best=pulls[0];if(best.special||best.ovr>=85)await slowReveal(pack,pulls);else await quickReveal(pack,pulls)};
PV.closeResults=()=>{const o=$('#overlay');o.className='overlay hidden';o.innerHTML='';PV.ui.screen='club';PV.render()};
function candidateOwned(slotId){const slot=D.SLOTS.find(s=>s.id===slotId);if(!slot)return[];return PV.owned().map(x=>x.p).filter(p=>PV.canPlay(p,slot.label)&&!PV.identityUsed(PV.state.squad,p.id,slotId)).sort((a,b)=>b.ovr-a.ovr||b.price-a.price)}
PV.openSquadPicker=slotId=>{const slot=D.SLOTS.find(s=>s.id===slotId),a=candidateOwned(slotId);PV.openSheet(`<span class="eyebrow">ESCOGER ${slot.label}</span><h2 style="margin:4px 0 10px">Mejor química o mejor media</h2>${a.length?`<div class="picker-grid">${a.map(p=>PV.card(p,{mini:true,button:false})).join('')}</div><div style="display:none">${a.map(p=>`<button data-pick-player="${p.id}" data-pick-slot="${slotId}"></button>`).join('')}</div>`:'<div class="empty">No tienes jugadores compatibles.</div>'}`);const cards=[...$('#sheetBody').querySelectorAll('.mini-card')];cards.forEach((c,i)=>c.onclick=()=>PV.pickSquad(slotId,a[i].id))};
PV.pickSquad=(slot,id)=>{const p=PV.byId(id);if(!p||PV.identityUsed(PV.state.squad,id,slot))return;PV.state.squad[slot]=id;PV.save();PV.closeSheet();PV.render()};
PV.autoXI=()=>{let sq={};for(const slot of D.SLOTS){let cand=PV.owned().map(x=>x.p).filter(p=>PV.canPlay(p,slot.label)&&!PV.identityUsed(sq,p.id,slot.id));let best=null,bestScore=-1;for(const p of cand.slice(0,45)){const test={...sq,[slot.id]:p.id},m=PV.squadMetrics(test),score=m.total*1000+m.rating*15+p.ovr;if(score>bestScore){best=p;bestScore=score}}if(best)sq[slot.id]=best.id}PV.state.squad=sq;PV.save();PV.render();PV.toast('Auto XI optimizado')};
PV.clearXI=()=>{PV.state.squad={};PV.save();PV.render()};
function draftPool(label,picks){const identities=new Set(Object.values(picks||{}).map(id=>PV.byId(id)?.identity));return D.PLAYERS.filter(p=>p.ovr>=75&&PV.canPlay(p,label)&&!identities.has(p.identity))}
function draftChoices(label,picks){let pool=draftPool(label,picks),out=[];for(let i=0;i<5&&pool.length;i++){pool.sort((a,b)=>b.ovr-a.ovr);let limit=Math.min(pool.length,Math.random()<.18?10:Math.random()<.55?28:pool.length),idx=Math.floor(Math.pow(Math.random(),1.45)*limit),p=pool.splice(idx,1)[0];out.push(p)}return out}
PV.startDraft=()=>{PV.state.draft={picks:{},started:Date.now()};PV.save();PV.render()};
PV.openDraftPick=slotId=>{const d=PV.state.draft,slot=D.SLOTS.find(s=>s.id===slotId);if(!d||d.picks[slotId])return;const a=draftChoices(slot.label,d.picks);PV.openSheet(`<span class="eyebrow">DRAFT PICK · ${slot.label}</span><h2 style="margin:4px 0 10px">Elige 1 de 5</h2><div class="draft-picks">${a.map(p=>PV.card(p,{mini:true,button:false})).join('')}</div>`);[...$('#sheetBody').querySelectorAll('.mini-card')].forEach((c,i)=>c.onclick=()=>{d.picks[slotId]=a[i].id;PV.save();PV.closeSheet();PV.render()})};
PV.finishDraft=()=>{const d=PV.state.draft;if(!d||Object.keys(d.picks||{}).length<11)return;const m=PV.squadMetrics(d.picks),reward=PV.draftReward(m.total);PV.state.draftCompletions++;PV.state.draftBest=Math.max(PV.state.draftBest,m.total);PV.state.packTokens[reward]=(PV.state.packTokens[reward]||0)+1;PV.state.xp+=180;PV.state.draft=null;PV.save();PV.render();PV.toast(`Draft ${m.total}/199 · +1 ${D.PACKS_V4.find(p=>p.id===reward)?.name}`)};
PV.resetDraft=()=>{PV.state.draft={picks:{},started:Date.now()};PV.save();PV.render()};
PV.previewSbc=id=>{const ch=PV.SBCS.find(x=>x.id===id),sol=PV.solveSbc(ch);if(!sol)return;const avg=(sol.reduce((s,x)=>s+x.p.ovr,0)/sol.length).toFixed(1),reward=D.PACKS_V4.find(p=>p.id===ch.reward)?.name;PV.openSheet(`<span class="eyebrow">SOLUCIÓN AUTOMÁTICA</span><h2 style="margin:4px 0">${PV.esc(ch.name)}</h2><p class="muted" style="font-size:7px;line-height:1.55;margin:8px 0">${sol.map(x=>`${x.p.ovr} ${PV.esc(x.p.name)}`).join(' · ')}</p><div class="reqs"><span class="req">GRL ${avg}</span><span class="req">→ ${PV.esc(reward)}</span><span class="req">SOLO DUPES</span></div><button class="btn" data-confirm-sbc="${id}" style="width:100%;margin-top:12px">ENTREGAR DUPLICADOS</button>`)};
PV.doSbc=id=>{const ch=PV.SBCS.find(x=>x.id===id);if(!ch||!PV.submitSbc(ch))return PV.toast('No cumples los requisitos');PV.closeSheet();PV.render();PV.toast(`SBC completado · +1 ${D.PACKS_V4.find(p=>p.id===ch.reward)?.name}`)};
PV.newQuiz=()=>{const pool=D.PLAYERS.filter(p=>p.ovr>=75&&!p.special),p=pool[Math.floor(Math.random()*pool.length)],set=new Set([p.ovr]);while(set.size<4){const d=Math.floor(Math.random()*7)-3;set.add(Math.max(75,Math.min(93,p.ovr+(d||1))))}PV.ui.quiz={p,opts:[...set].sort(()=>Math.random()-.5),answered:false};if(PV.ui.screen==='academy')PV.render()};
PV.answerQuiz=(v,btn)=>{const q=PV.ui.quiz;if(!q||q.answered)return;q.answered=true;const ok=v===q.p.ovr;if(ok){PV.state.quizStreak++;PV.state.quizCorrect++;PV.state.quizBest=Math.max(PV.state.quizBest,PV.state.quizStreak);PV.state.coins+=150;PV.state.xp+=15}else PV.state.quizStreak=0;PV.save();document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;if(+b.dataset.answer===q.p.ovr)b.classList.add('good')});if(!ok)btn.classList.add('bad');setTimeout(()=>PV.newQuiz(),900)};
PV.applyFilters=()=>{const f=PV.ui.filters;f.min=+$('#fMin').value;f.quality=$('#fQuality').value;f.pos=$('#fPos').value;f.league=$('#fLeague').value;f.dupes=$('#fDupes').value;f.sort=$('#fSort').value;PV.closeSheet();PV.render()};
})();