(function(){
'use strict';
const PV=window.PV4;
PV.state.clubLogos=PV.state.clubLogos||{};PV.state.leagueLogos=PV.state.leagueLogos||{};
const teamAliases={'CE Sabadell FC':'Sabadell','R. Valladolid CF':'Real Valladolid','UD Almería':'Almeria','Cádiz CF':'Cadiz','Real Sociedad B':'Real Sociedad B','RCD Mallorca':'Mallorca'};
const playerAliases={'Azzedine Ounahi':'Azzedine Ounahi','Viktor Tsygankov':'Viktor Tsyhankov','Dinko Horkaš':'Dinko Horkas','Álvaro Tejero':'Alvaro Tejero','Álex Muñoz':'Alex Munoz','Rubén Alcaraz':'Ruben Alcaraz','José Arnáiz':'Jose Arnaiz','Raíllo':'Antonio Raillo','Samú Costa':'Samu Costa'};
const sabadell='https://drop-assets.ea.com/images/aIrhRNIaKr0UWY3sbwxHo/1fa8ec800517b3804005ad84e26c4d80/l15021.png';
PV.clubLogoSync=club=>club==='CE Sabadell FC'?sabadell:(PV.state.clubLogos[club]||null);
PV.clubLogoFor=async club=>{if(!club)return null;if(club==='CE Sabadell FC')return sabadell;if(PV.state.clubLogos[club])return PV.state.clubLogos[club];try{const q=encodeURIComponent(teamAliases[club]||club),r=await fetch(`https://www.thesportsdb.com/api/v1/json/123/searchteams.php?t=${q}`),j=await r.json(),teams=j?.teams||[],norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),target=norm(club),t=teams.find(x=>target.includes(norm(x.strTeam))||norm(x.strTeam).includes(target))||teams[0],url=t?.strBadge||t?.strLogo||null;if(url){PV.state.clubLogos[club]=url;PV.save();return url}}catch{}return null};
PV.leagueLogoFor=async league=>{if(!league)return null;if(PV.state.leagueLogos[league])return PV.state.leagueLogos[league];if(league!=='LALIGA HYPERMOTION')return null;try{const r=await fetch('https://www.thesportsdb.com/api/v1/json/123/search_all_leagues.php?c=Spain&s=Soccer'),j=await r.json(),a=j?.countries||j?.leagues||[],x=a.find(l=>/segunda|laliga.?2|hypermotion/i.test(`${l.strLeague||''} ${l.strLeagueAlternate||''}`)),url=x?.strBadge||x?.strLogo||null;if(url){PV.state.leagueLogos[league]=url;PV.save();return url}}catch{}return null};
const oldPhoto=PV.photoFor;PV.photoFor=async p=>{if(PV.state.photos[p.id])return PV.state.photos[p.id];const raw=[p.searchName||p.name,playerAliases[p.name],String(p.name).normalize('NFD').replace(/[\u0300-\u036f]/g,'')].filter(Boolean);for(const name of [...new Set(raw)]){try{const r=await fetch(`https://www.thesportsdb.com/api/v1/json/123/searchplayers.php?p=${encodeURIComponent(name)}`),j=await r.json(),arr=j?.player||[],norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),target=norm(p.name),club=norm(teamAliases[p.club]||p.club),exact=arr.find(x=>(target.includes(norm(x.strPlayer))||norm(x.strPlayer).includes(target))&&(!club||norm(x.strTeam).includes(club)||club.includes(norm(x.strTeam)))),a=exact||arr.find(x=>target.includes(norm(x.strPlayer))||norm(x.strPlayer).includes(target))||arr[0],url=a?.strCutout||a?.strThumb||null;if(url){PV.state.photos[p.id]=url;PV.save();return url}}catch{}}return oldPhoto?oldPhoto(p):null};
const oldHydrate=PV.hydrate;PV.hydrate=root=>{oldHydrate?.(root);const scope=root||document;const clubs=[...new Set([...scope.querySelectorAll('[data-club-badge]')].map(n=>n.dataset.clubBadge))].slice(0,10);clubs.forEach(async club=>{const url=await PV.clubLogoFor(club);if(!url)return;document.querySelectorAll(`[data-club-badge="${CSS.escape(club)}"]`).forEach(n=>n.innerHTML=`<img src="${PV.esc(url)}" alt="" loading="lazy">`)});const leagues=[...new Set([...scope.querySelectorAll('[data-league-badge]')].map(n=>n.dataset.leagueBadge))].slice(0,3);leagues.forEach(async league=>{const url=await PV.leagueLogoFor(league);if(!url)return;document.querySelectorAll(`[data-league-badge="${CSS.escape(league)}"]`).forEach(n=>n.innerHTML=`<img src="${PV.esc(url)}" alt="" loading="lazy">`)})};
})();