(function(){
'use strict';
const PV=window.PV4,$=s=>document.querySelector(s),SBC_FORM=PV.FORMATIONS['4-4-2'];
function build(){const id=PV.ui.sbcActive;return id?(PV.state.sbcBuilds?.[id]||{}):{}}
function selectedIdentitySet(b,exceptSlot=null){const set=new Set();for(const [slot,id] of Object.entries(b||{})){if(slot===exceptSlot)continue;const p=PV.byId(id);if(p)set.add(p.identity)}return set}
function availableUniqueDupes(slotId){const b=build(),slot=SBC_FORM.find(s=>s.id===slotId),used=selectedIdentitySet(b,slotId);if(!slot)return[];return PV.owned().filter(({count,p})=>count>1&&PV.canPlay(p,slot.label)&&!used.has(p.identity)).map(x=>x.p).sort((a,b)=>b.ovr-a.ovr||b.price-a.price)}
PV.openSbcSlot=slotId=>{const ch=PV.SBC_MANUAL.find(x=>x.id===PV.ui.sbcActive);if(!ch)return;const b=build(),a=availableUniqueDupes(slotId),slot=SBC_FORM.find(s=>s.id===slotId);PV.openSheet(`<span class="eyebrow">SBC · ${slot.label}</span><h2 style="margin:4px 0 6px">Elige un duplicado</h2><p class="muted pv8-sbc-law">Un mismo futbolista solo puede aparecer una vez en la plantilla, aunque tengas varias copias.</p>${a.length?`<div class="picker-grid">${a.map(p=>PV.card(p,{mini:true,button:false,count:PV.state.collection[p.id]})).join('')}</div>`:'<div class="empty">No tienes duplicados compatibles y únicos para esta posición.</div>'}`);[...$('#sheetBody').querySelectorAll('.mini-card')].forEach((c,i)=>c.onclick=()=>{b[slotId]=a[i].id;PV.save();PV.closeSheet();PV.render()})};
PV.autoSbc=()=>{const ch=PV.SBC_MANUAL.find(x=>x.id===PV.ui.sbcActive);if(!ch)return;const b={},usedIdentity=new Set();for(const slot of SBC_FORM){let candidates=PV.owned().filter(({count,p})=>count>1&&PV.canPlay(p,slot.label)&&!usedIdentity.has(p.identity)&&(!ch.req.tier||p.tier===ch.req.tier)).map(x=>x.p).sort((a,b)=>a.ovr-b.ovr||a.price-b.price);if(!candidates.length&&ch.req.tier)candidates=PV.owned().filter(({count,p})=>count>1&&PV.canPlay(p,slot.label)&&!usedIdentity.has(p.identity)).map(x=>x.p).sort((a,b)=>a.ovr-b.ovr||a.price-b.price);const pick=candidates[0];if(pick){b[slot.id]=pick.id;usedIdentity.add(pick.identity)}}PV.state.sbcBuilds[ch.id]=b;PV.save();PV.render()};
const oldSubmit=PV.submitManualSbc;PV.submitManualSbc=()=>{const b=build(),players=Object.values(b).map(PV.byId).filter(Boolean),ids=players.map(p=>p.identity);if(new Set(ids).size!==ids.length)return PV.toast('No puedes usar al mismo jugador dos veces');return oldSubmit()};
function cleanBuilds(){for(const [ch,b] of Object.entries(PV.state.sbcBuilds||{})){const seen=new Set();for(const slot of Object.keys(b)){const p=PV.byId(b[slot]);if(!p||seen.has(p.identity))delete b[slot];else seen.add(p.identity)}}}
function repaintField(selector,squad,slots,metrics){document.querySelectorAll(selector).forEach(btn=>{const slotId=btn.dataset.slot||btn.dataset.sbcSlot,p=PV.byId(squad?.[slotId]);if(!p)return;btn.innerHTML=PV.fieldCard(p,metrics.per?.[slotId]||0)});PV.hydrate?.($('#screen'))}
const oldRender=PV.render;PV.render=()=>{cleanBuilds();oldRender();if(PV.ui.screen==='squad'){const slots=PV.FORMATIONS[PV.state.formation||'4-3-3'],m=PV.squadMetrics(PV.state.squad);repaintField('[data-slot]:not(.empty)',PV.state.squad,slots,m)}if(PV.ui.screen==='sbc'&&PV.ui.sbcActive){const b=build(),m=PV.metricsForSlots(b,SBC_FORM);repaintField('[data-sbc-slot]:not(.empty)',b,SBC_FORM,m)}};
})();