import fs from 'node:fs';
import vm from 'node:vm';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const ORDER=['js/data.js','v4/content.js','v4/core.js','v5/rules.js','v6/content.js','v7/content.js','v8/content.js','v9/content.js','v9/cleanup.js','v8/rules.js','v12/content.js','v14/content.js','v4/ui.js','v5/card-ui.js','v6/card-ui.js','v7/card-ui.js','v8/assets.js','v9/assets.js','v10/assets.js','v11/assets.js','v12/assets.js','v13/assets.js','v14/assets.js','v8/card-ui.js','v9/card-ui.js','v13/card-ui.js'];
for(const f of ORDER){assert(fs.existsSync(f),`missing ${f}`);new Function(fs.readFileSync(f,'utf8'))}
const store={};const classList={add(){},remove(){},toggle(){},contains(){return false}};const node=()=>({innerHTML:'',dataset:{},classList,querySelector(){return null},querySelectorAll(){return[]},closest(){return null},remove(){},addEventListener(){}});
const document={querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},dispatchEvent(){},createElement(){return node()}};
class IO{observe(){}unobserve(){}disconnect(){}}
const ctx={window:{},document,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v)},CustomEvent:function(){},IntersectionObserver:IO,Intl,structuredClone,console,setTimeout,clearTimeout,Math,CSS:{escape:s=>String(s)},navigator:{vibrate(){}},location:{protocol:'https:'},fetch:async()=>({ok:true,json:async()=>({player:[],teams:[],countries:[]})}),Date};
ctx.window.window=ctx.window;ctx.window.document=document;ctx.window.IntersectionObserver=IO;vm.createContext(ctx);for(const f of ORDER)vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const D=ctx.window.PACKVERSE_DATA,PV=ctx.window.PV4;
const by=n=>D.PLAYERS.find(p=>p.name===n&&!p.special);
assert(by('Karim Adeyemi')?.club==='FC Barcelona','Adeyemi current club regression');
assert(by('João Cancelo')?.club==='FC Barcelona','Cancelo current club regression');
assert(by('Rodri')?.club==='FC Barcelona','Rodri current club regression');
assert(by('Gabriel Jesus')?.club==='FC Barcelona','Gabriel Jesus current club regression');
assert(by('Anthony Gordon')?.club==='FC Barcelona','Anthony Gordon current club regression');
for(const n of ['Joan García','Dominik Livaković','Brian Fariñas','Xavi Espart','Jesse Bisiwu','Hamza Abdelkarim'])assert(by(n),`missing real pool addition ${n}`);
const tiers=Object.fromEntries(['bronze','silver','gold','special'].map(t=>[t,D.PLAYERS.filter(p=>p.tier===t).length]));
assert(D.PLAYERS.length>=280,`pool expansion too small: ${D.PLAYERS.length}`);
assert(tiers.bronze>=39,'bronze progression pool regressed');assert(tiers.silver>=20,'silver pool too small');assert(tiers.gold>=120,'gold pool too small');
const asset=fs.readFileSync('v14/assets.js','utf8');
assert(asset.includes("hit?.strCutout||null"),'v14 must use cutout only');
assert(!asset.includes('strThumb')&&!asset.includes('strRender'),'generic portrait/render fallback reintroduced');
assert(asset.includes("meta.club===p.club&&meta.kind==='cutout'"),'cached photo is not tied to current club');
assert(asset.includes('Rectangular internet photos are intentionally discarded'),'rectangular-photo policy missing');
assert(ctx.window.PV14_ASSET_AUDIT?.rectangularPhotosAllowed===false,'runtime policy allows rectangular photos');
assert(PV.state.assetPolicyVersion===14,'asset cache was not migrated to policy v14');
const cov=PV.assetCoverage();assert(cov.policy.includes('CUTOUT ONLY'),'coverage policy mismatch');
console.log(`PackVerse v0.14 integrity smoke OK · ${D.PLAYERS.length} cards · bronze ${tiers.bronze} · silver ${tiers.silver} · gold ${tiers.gold} · strict current-club cutout-only art`);
