import fs from 'node:fs';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
for(const f of ['v9/assets.js','v10/assets.js','v11/assets.js','v12/assets.js','v14/assets.js','v15/assets.js','v17/assets.js','index.html','sw.js'])assert(fs.existsSync(f),`missing ${f}`);
const v9=fs.readFileSync('v9/assets.js','utf8'),v10=fs.readFileSync('v10/assets.js','utf8'),v11=fs.readFileSync('v11/assets.js','utf8'),v12=fs.readFileSync('v12/assets.js','utf8'),v14=fs.readFileSync('v14/assets.js','utf8'),v15=fs.readFileSync('v15/assets.js','utf8'),v17=fs.readFileSync('v17/assets.js','utf8'),html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');
for(const js of [v9,v10,v11,v12,v14,v15,v17])new Function(js);
assert(v9.includes('Number(PV.state.assetMatchVersion||0)<9'),'V9 match migration is not monotonic');
assert(v10.includes('Number(PV.state.assetMatchVersion||0)<10'),'V10 match migration is not monotonic');
assert(v11.includes('Number(PV.state.assetPolicyVersion||0)<11'),'V11 policy migration is not monotonic');
assert(v12.includes('Number(PV.state.assetPolicyVersion||0)<12'),'V12 migration is not monotonic');
assert(v14.includes('Number(PV.state.assetPolicyVersion||0)<14'),'V14 migration is not monotonic');
assert(v15.includes('Number(PV.state.assetPolicyVersion||0)<15'),'V15 migration is not monotonic');
assert(!v9.includes('assetMatchVersion!==9')&&!v10.includes('assetMatchVersion!==10'),'legacy match layer can wipe newer cached photos/logos');
assert(!v11.includes('assetPolicyVersion!==11')&&!v12.includes('assetPolicyVersion!==12')&&!v14.includes('assetPolicyVersion!==14')&&!v15.includes('assetPolicyVersion!==15'),'older policy layer can wipe later-policy assets');
assert(html.includes('<script src="v17/assets.js"></script>'),'V17 assets not loaded');
const cacheVersion=Number(sw.match(/const CACHE='packverse27-v(\d+)-/)?.[1]||0);assert(cacheVersion>=17&&sw.includes('./v17/assets.js'),`V17 PWA guarantee missing under cache v${cacheVersion||'?'}`);
assert(v17.includes('assetRecoveryV17')&&v17.includes('photoMissesV15={}'),'one-time false-negative recovery missing');
assert(v17.includes('IntersectionObserver')&&v17.includes("rootMargin:'520px 0px'"),'viewport-lazy player hydration missing');
assert(!v17.includes('oldHydrate?.(root)'),'V17 final hydrator must not call V16 eager hydrator');
for(const [club,id] of [['Aston Villa',58],['Everton',62],['Brentford',402],['Brighton',397],['Crystal Palace',354],['West Ham',563],['Wolverhampton',76],['Leeds United',341],['Burnley',328]])assert(v17.includes(`'${club}':${id}`),`deterministic crest missing ${club}`);
assert(v17.includes('safeCachedPhoto')&&v17.includes('photoMetaV16')&&v17.includes('photoMetaV15'),'safe cached-photo persistence check missing');
console.log(`PackVerse V0.17 static smoke OK under PWA cache v${cacheVersion} · monotonic migrations · viewport-lazy photo lookup · deterministic PL crest expansion`);
