import fs from 'node:fs';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
for(const f of ['v16/content.js','v16/assets.js','v16/visuals.css','index.html','sw.js'])assert(fs.existsSync(f),`missing ${f}`);
const content=fs.readFileSync('v16/content.js','utf8');
const assets=fs.readFileSync('v16/assets.js','utf8');
const css=fs.readFileSync('v16/visuals.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
new Function(content);new Function(assets);
assert(html.includes('v16/content.js')&&html.includes('v16/assets.js')&&html.includes('v16/visuals.css'),'V0.16 layer is not fully loaded');
assert(assets.includes("'dominik livakovic':'https://www.fcbarcelona.com/photo-resources/"),'Livakovic is not pinned to a current Barça official cutout');
assert(!/dominik livakovic[^\n]+girona/i.test(assets),'Livakovic Girona art regression detected');
assert(assets.includes('RECENT_TRANSFER_GUARD'),'recent-transfer stale-shirt guard missing');
assert(assets.includes("kind:'shared-base-cutout'")&&content.includes('baseCardId'),'IF/base artwork sharing missing');
assert(!assets.includes('strThumb')&&!assets.includes('strRender'),'unsafe portrait/render fallback reintroduced');
for(const league of ['LaLiga EA Sports','LALIGA HYPERMOTION','Premier League','Bundesliga','Serie A','Ligue 1'])assert(assets.includes(`'${league}'`),`league identity resolver missing ${league}`);
assert(css.includes('.pv16-has-asset')&&css.includes('border-radius:0!important'),'identity slots can regress to circular badges');
assert(css.includes('.pv16-player-art'),'V0.16 player-art profile missing');
assert(sw.includes("packverse27-v16-card-assets"),'PWA cache was not bumped to V0.16');
for(const f of ['./v16/visuals.css','./v16/content.js','./v16/assets.js'])assert(sw.includes(f),`PWA core missing ${f}`);
console.log('PackVerse V0.16 smoke OK · Livakovic current Barça art · stale-transfer guard · IF/base image reuse · expanded identity coverage');
