import fs from 'node:fs';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
for(const f of ['v12/assets.js','v14/assets.js','v15/assets.js','v17/assets.js','index.html','sw.js'])assert(fs.existsSync(f),`missing ${f}`);
const v12=fs.readFileSync('v12/assets.js','utf8'),v14=fs.readFileSync('v14/assets.js','utf8'),v15=fs.readFileSync('v15/assets.js','utf8'),v17=fs.readFileSync('v17/assets.js','utf8'),html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');
new Function(v12);new Function(v14);new Function(v15);new Function(v17);
assert(v12.includes('Number(PV.state.assetPolicyVersion||0)<12'),'V12 migration is not monotonic');
assert(v14.includes('Number(PV.state.assetPolicyVersion||0)<14'),'V14 migration is not monotonic');
assert(v15.includes('Number(PV.state.assetPolicyVersion||0)<15'),'V15 migration is not monotonic');
assert(!v12.includes('assetPolicyVersion!==12')&&!v14.includes('assetPolicyVersion!==14')&&!v15.includes('assetPolicyVersion!==15'),'older layer can still wipe later-policy photos');
assert(html.includes('<script src="v17/assets.js"></script>'),'V17 assets not loaded');
assert(sw.includes("packverse27-v17-asset-persistence")&&sw.includes('./v17/assets.js'),'V17 PWA cache missing');
assert(v17.includes('assetRecoveryV17')&&v17.includes('photoMissesV15={}'),'one-time false-negative recovery missing');
assert(v17.includes('IntersectionObserver')&&v17.includes("rootMargin:'520px 0px'"),'viewport-lazy player hydration missing');
assert(!v17.includes('oldHydrate?.(root)'),'V17 final hydrator must not call V16 eager hydrator');
for(const [club,id] of [['Aston Villa',58],['Everton',62],['Brentford',402],['Brighton',397],['Crystal Palace',354],['West Ham',563],['Wolverhampton',76],['Leeds United',341],['Burnley',328]])assert(v17.includes(`'${club}':${id}`),`deterministic crest missing ${club}`);
assert(v17.includes('safeCachedPhoto')&&v17.includes('photoMetaV16')&&v17.includes('photoMetaV15'),'safe cached-photo persistence check missing');
console.log('PackVerse V0.17 static smoke OK · monotonic V12/V14/V15 migration · viewport-lazy photo lookup · one-time retry recovery · deterministic PL crest expansion');
