import fs from 'node:fs';
import vm from 'node:vm';
const files=['js/data.js','v4/content.js','v4/core.js','v5/rules.js','v6/content.js','v7/content.js','v8/content.js','v9/content.js','v9/cleanup.js','v8/rules.js','v4/ui.js','v5/card-ui.js','v6/card-ui.js','v7/card-ui.js','v8/assets.js','v9/assets.js','v10/assets.js','v11/assets.js','v8/card-ui.js','v9/card-ui.js','v4/game.js','v5/game-polish.js','v6/game.js','v6/systems.js','v8/systems.js','v6/cleanup.js','v4/main.js'];
for(const f of files){const src=fs.readFileSync(f,'utf8');new Function(src)}
const store={};
const ctx={window:{},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},document:{dispatchEvent(){},querySelectorAll(){return[]}},CustomEvent:function(){},Intl,structuredClone,console,setTimeout,clearTimeout,fetch:async()=>({json:async()=>({})}),Math,CSS:{escape:s=>s}};
vm.createContext(ctx);
for(const f of ['js/data.js','v4/content.js','v4/core.js','v5/rules.js','v6/content.js','v7/content.js','v8/content.js','v9/content.js','v9/cleanup.js','v8/rules.js','v9/assets.js','v10/assets.js','v11/assets.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const D=ctx.window.PACKVERSE_DATA,PV=ctx.window.PV4;
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
assert(D.PLAYERS.length>=200,`player pool too small: ${D.PLAYERS.length}`);
assert(new Set(D.PLAYERS.map(p=>p.id)).size===D.PLAYERS.length,'duplicate player ids');
assert(D.TOTW.length>=8,`TOTW pool too small: ${D.TOTW.length}`);
assert(D.PACKS_V4.some(p=>p.id==='basic'&&p.free),'missing free basic pack');
assert(D.PACKS_V4.some(p=>p.id==='totw'&&p.specialOnly),'missing TOTW pack');
assert(D.PACKS_V4.some(p=>p.id==='gold3'&&p.tokenOnly),'missing SBC gold reward pack');
assert(D.SLOTS.length===11,'squad must contain 11 slots');
assert(D.PLAYERS.every(p=>p.cardType&&p.rarityLabel&&p.league),'missing card metadata');
const qualities=new Set(D.PLAYERS.map(p=>p.cardType));for(const q of ['bronze-common','bronze-rare','silver-common','silver-rare','gold-common','gold-rare','totw'])assert(qualities.has(q),`missing quality ${q}`);
const femaleNames=['Alexia Putellas','Aitana Bonmatí','Khadija Shaw','Ewa Pajor','Caroline Graham Hansen'];for(const n of femaleNames)assert(!D.PLAYERS.some(p=>p.name===n),`female card still active in male-only pool: ${n}`);
assert(!D.PLAYERS.some(p=>p.simulated&&!p.special&&p.ovr<75),'fictional low-rated base card leaked into live pool');
const hyper=D.PLAYERS.filter(p=>p.league==='LALIGA HYPERMOTION'&&!p.special),hyperTeams=new Set(hyper.map(p=>p.club));
assert(hyper.length>=110,`Hypermotion pool too small: ${hyper.length}`);assert(hyperTeams.size>=22,`Hypermotion team variety too low: ${hyperTeams.size}`);
for(const n of ['Azzedine Ounahi','Sergi Darder','Arribas','Kirian','Nolaskoain','Álvaro Tejero','Gumbau','Julien Ponceau','Izeta','Rober','Carracedo','José Gragera','Matos','Iñigo Córdoba','Fidel','Pau López','Hugo González','Aarón Escandell','Juan Ferney Otero','Mauro Pittón'])assert(hyper.some(p=>p.name===n),`missing Hypermotion card ${n}`);
const sabadell=hyper.filter(p=>p.club==='CE Sabadell FC');assert(sabadell.length>=18,`CE Sabadell pool too small: ${sabadell.length}`);
assert(PV.FORMATIONS&&Object.keys(PV.FORMATIONS).length>=6,'not enough formations');for(const [name,slots] of Object.entries(PV.FORMATIONS))assert(slots.length===11,`${name} must have 11 slots`);
const cardSrc=fs.readFileSync('v9/card-ui.js','utf8');assert(cardSrc.includes('PV.fieldCard')&&cardSrc.includes('PV.cardClass(p)'),'field cards must inherit exact rarity');assert(cardSrc.includes('pv9-card')&&cardSrc.includes('pv9-field-card'),'v0.9 card hooks missing');
const asset10=fs.readFileSync('v10/assets.js','utf8');assert(asset10.includes("'Bayern München':'https://drop-assets.ea.com"),'Bayern must use trusted football crest');assert(asset10.includes("'Inter':'https://intermilan.bynder.com"),'Inter must use official Inter source');assert(asset10.includes("strSport||'').toLowerCase()==='soccer'"),'remote crest fallback must reject non-football teams');
const asset11=fs.readFileSync('v11/assets.js','utf8');const a11=ctx.window.PV11_ASSETS;assert(a11&&Object.keys(a11.OFFICIAL_PLAYER_PHOTOS).length>=18,'v0.11 needs verified current-shirt player art');assert(!asset11.includes('searchplayers.php'),'v0.11 must not reintroduce unverified player-photo search');assert(asset11.includes('flagcdn.com')&&PV.flag('Inglaterra').includes('gb-eng.svg'),'England must share the same image-flag system');assert(a11.OFFICIAL_LEAGUE_LOGOS['LALIGA HYPERMOTION']&&a11.OFFICIAL_LEAGUE_LOGOS['LaLiga EA Sports'],'official LALIGA competition marks missing');assert(PV.state.leagueLogos['LALIGA HYPERMOTION'],'Hypermotion logo must be available synchronously');assert(asset11.includes('leagueOK(t.strLeague,league)'),'club fallback must verify expected league');assert(asset11.includes('Number(PV.state.assetPolicyVersion||0)<11'),'V11 stale-cache migration must be monotonic');assert(!asset11.includes('assetPolicyVersion!==11'),'V11 exact-version purge regression reintroduced');
const systemSrc=fs.readFileSync('v8/systems.js','utf8');assert(systemSrc.includes('usedIdentity')&&systemSrc.includes("new Set(ids).size!==ids.length"),'SBC duplicate-player identity law missing');
const css11=fs.readFileSync('v11/styles.css','utf8');for(const x of ['container-type:inline-size','.pv11-flag','@media(min-width:900px)','grid-template-columns:92px minmax(0,1fr)','display:flex!important','max-height:calc(100dvh - 48px)'])assert(css11.includes(x),`v0.11 responsive/card system missing ${x}`);assert(css11.includes('.pv7-card .pv7-stats b')&&css11.includes('cqw'),'card typography must scale from card width');
const m=PV.squadMetrics({});assert(m.rating===0&&m.chemistry===0&&m.total===0,'empty squad metrics invalid');assert(m.total<=199,'squad total can exceed 199');
assert(PV.SBCS.every(s=>PV.solveSbc(s)===null),'empty club should not solve SBC');
const daily=D.PACKS_V4.find(p=>p.id==='daily');assert(daily?.rule,'daily pack missing odds rule');const daily85=daily.rule.bands.filter(b=>b[0]>=85).reduce((s,b)=>s+b[2],0),daily87=daily.rule.bands.filter(b=>b[0]>=87).reduce((s,b)=>s+b[2],0);assert(daily85<=0.006,'daily 85+ odds too generous');assert(daily87<=0.001,'daily 87+ odds too generous');
for(const sp of D.TOTW){const base=D.PLAYERS.find(p=>!p.special&&p.identity===sp.identity);if(base&&base.ovr>=86)assert(sp.ovr===base.ovr+1,`${sp.name} TOTW should be +1 OVR from high-rated base`)}
console.log(`PackVerse v0.11 OK: ${D.PLAYERS.length} male cards, ${hyper.length} Hypermotion cards, verified art + league assets + desktop Companion`);
